#
# APP settings
#
spring.application.name=ecom-platform-2
spring.main.banner-mode=off
#
# Datasource, PostgreSQL
#
spring.datasource.url=jdbc:postgresql://localhost:5432/econ-platform-2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=dev
spring.datasource.password=test1234
#
# JPA
#
spring.jpa.hibernate.ddl-auto=update
#
# Logs
# show JPA/Hibernate logging messages
#
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true